--Q1. What is the total revenue generated by male vs. female customers?
SELECT "Gender",
       SUM("Purchase Amount (USD)") AS revenue
FROM matches
GROUP BY "Gender";


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT "Customer ID",
       "Purchase Amount (USD)"
FROM matches
WHERE "Discount Applied" = 'Yes'
  AND CAST("Purchase Amount (USD)" AS NUMERIC) >= (
        SELECT AVG(CAST("Purchase Amount (USD)" AS NUMERIC))
        FROM matches
      );

select * from matches;
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    "Item Purchased",
    AVG("Review Rating") AS average_rating
FROM matches
GROUP BY "Item Purchased"
ORDER BY average_rating DESC
LIMIT 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS average_purchase_amount
FROM matches
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT 
    "Subscription Status",
    AVG("Purchase Amount (USD)") AS average_spend,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM matches
GROUP BY "Subscription Status";

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    "Item Purchased",
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        (SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)::numeric 
        / COUNT(*)::numeric) * 100, 
        2
    ) AS discount_percentage
FROM matches
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT 
    CASE 
        WHEN "Previous Purchases" = 0 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 1 AND 10 THEN 'Returning'
        WHEN "Previous Purchases" > 10 THEN 'Loyal'
    END AS customer_segment,
    COUNT(*) AS segment_count
FROM matches
GROUP BY customer_segment
ORDER BY segment_count DESC;



 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    CASE 
        WHEN "Previous Purchases" > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    
    COUNT(*) AS total_customers,
    
    SUM(CASE WHEN "Subscription Status" = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
    
    ROUND(
        (SUM(CASE WHEN "Subscription Status" = 'Yes' THEN 1 ELSE 0 END)::numeric 
        / COUNT(*)::numeric) * 100,
        2
    ) AS subscription_rate_percentage

FROM matches
GROUP BY customer_type
ORDER BY subscription_rate_percentage DESC;


